--CREATE TABLE PERSON
--(
--    ID INTEGER NOT NULL,
--    NAME VARCHAR(255) NOT NULL,
--    LOCATION VARCHAR(225),
--    BIRTH_DATE TIMESTAMP,
--    PRIMARY KEY(ID)
--);

INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES (51,'Hardik', 'Mundra', sysdate());
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES (52,'Mom', 'Morbi', sysdate());
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES (53,'Papa', 'Morbi', sysdate());
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES (54,'Sneha', 'Pune', sysdate());
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES (55,'ReenaBhabhi', 'Mundra', sysdate());
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES (56,'Nirav', 'Pune', sysdate());
