CREATE TABLE PERSON
(
    ID INTEGER NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    LOCATION VARCHAR(225),
    BIRTH_DATE TIMESTAMP,
    PRIMARY KEY(ID)
);

INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES (1,'Hardik', 'Mundra', sysdate());
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES (2,'Mom', 'Morbi', sysdate());
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES (3,'Papa', 'Morbi', sysdate());
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES (4,'Sneha', 'Pune', sysdate());
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES (5,'ReenaBhabhi', 'Mundra', sysdate());
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES (6,'Nirav', 'Pune', sysdate());
